### ISSUE TITLE
2 PC Setup

### ISSUE THREAD

**Issue by nibalizer** [cloud-platforms-streaming/streaming-docs#2]
Why is the standard recommendation for a 2pc setup? Shouldn't that be an exception and not the default? It's totally possible to stream by yourself with OBS or bring in a co-presenter via zoom locally.

**Comment by chris-short** [comment]
My MacBook Air would keel over if I tried to do everything from it even with an external GPU. The CPU just isn't enough. My 8th gen i3 NUC that I use for streaming was struggling during a test this week.

I completely agree it's possible to do it from one, powerful enough computer. But, I personally couldn't and I have seen that many other streamers use two computers as well.

I've noted this in the new [Streaming Guide](https://github.com/cloud-platforms-streaming/streaming-docs/blob/master/streamers-guide.md).
